### ISSUE TITLE
ssmtp.conf.erb template resource flexibility

### ISSUE THREAD

**Issue by drenalin23** [mmmorris1975/ssmtp2#1]
It would be nice to put owner, group and mode into attributes so that folks wrapping the cookbook in a role could override those settings easily.

**Comment by mmmorris1975** [comment]
Apologies for the delay getting back to you.  Easy enough change, should have a new version ready for you by the morning.

**Comment by mmmorris1975** [comment]
Released as version 0.3.1, is on supermarket at: https://supermarket.chef.io/cookbooks/ssmtp2/versions/0.3.1
